Day4Repo Solution/Day4Repo/ViewModels/ErrorViewModel.cs
namespace Day4Repo.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Day4Repo Solution/Day4Repo/Controllers/DepatmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Day4Repo.BLL.interfaces;
using Day4Repo.DAL.Model;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Day4Repo.PL.Controllers
{
    public class DepatmentController : Controller
    {
        private readonly IDepartmentReposatory _departmentRepo;
        public DepatmentController(IDepartmentReposatory departmentRepo)
        {
            _departmentRepo = departmentRepo;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var deps = _departmentRepo.GetAll();
            return View(deps);
        }
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            else
            {
                var dep = _departmentRepo.Get(id.Value);
                return View(dep);
            }
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Department dep)
        {
            _departmentRepo.Create(dep);
            return RedirectToAction("Index");
        }

        public IActionResult Update(Department dep)
        {
            
                var deps = _departmentRepo.Update(dep);
                return View(deps);
            
        }
        public IActionResult Delete(Department dep)
        {

            var deps = _departmentRepo.Delete(dep);
            return View(deps);

        }
    }
}

Day4Repo Solution/Day4Repo/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Day4Repo.Models;

namespace Day4Repo.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Day4Repo Solution/Day4Repo/Views/Department/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Department
@{
}


<h2> Add New Department </h2>

<form asp-action="Create">
    <div class="form-control">
        <label asp-for="Code" class="form-control"></label>
        <input asp-for="Code" class="form-control" />
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>
    <div class="form-control">
        <label asp-for="Name" class="form-control"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-control">
        <label asp-for="CreatedAt" class="form-control"></label>
        <input asp-for="CreatedAt" class="form-control" />
        <span asp-validation-for="CreatedAt" class="text-danger"></span>
    </div>

    <input type="submit" class="btn btn-primary" />
    | <a asp-action="Index" class="btn btn-dark"> Back to List</a>
</form>

Day4Repo Solution/Day4Repo/Views/Department/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Department
@{
}

<div class="card">
    <h2 class="card-title"> @Model.Name </h2>
    <h3 class="card-subtitle"> @Model.Code </h3>
    <p class="card-body"> @Model.CreatedAt </p>
</div>

Day4Repo Solution/Day4Repo/Views/Department/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model List<Department>
@{
}

<h2> Departments List </h2>
<a asp-action="Create" class="btn btn-primary"> Create New Department</a>
@if (Model.Count() > 0)
{

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <td>code </td>
                <td>Name </td>
                <td> DateCreated </td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td> @item.Code </td>

                    <td> @item.Name </td>
                    <td> @item.CreatedAt </td>
                    <td> <a asp-controller="Department" asp-action="Details" asp-route-id="@item.Id" class="btn btn-sucess"> Details  </a></td>
                    <td> <a asp-controller="Department" asp-action="Update" class="btn btn-info"> Update  </a> </td>
                    <td> <a asp-controller="Department" asp-action="Delete" class="btn btn-danger"> Delete  </a> </td>
                </tr>
            }

        </tbody>
    </table>
}
else
{
    <div class="card bg-dark text-light">
        <h2>  No Departments Available </h2>
    </div>
}

Day4Repo Solution/Day4Repo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Day4Repo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Day4Repo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Day4Repo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Depatment" asp-action="Index">Department</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Day4Repo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>