FullToDoWebsite solution/FullToDoWebsite/Models/ErrorViewModel.cs
namespace FullToDoWebsite.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

FullToDoWebsite solution/FullToDoWebsite/Models/ToDoTasks.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FullToDoWebsite.Models
{
	public class ToDoTasks
	{
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Task_id { get; set; }
        [Required (ErrorMessage ="Task is required, please enter your task")]
        public string? Task_todo { get; set; }
        public string? Task_description { get; set; }
        public DateTime Task_DueDate { get; set; }
        public bool Task_Status { get; set; }

    }
}

FullToDoWebsite solution/FullToDoWebsite/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FullToDoWebsite.Models;

namespace FullToDoWebsite.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

FullToDoWebsite solution/FullToDoWebsite/Controllers/ToDoTasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FullToDoWebsite.Data;
using FullToDoWebsite.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FullToDoWebsite.Controllers
{
    public class ToDoTasksController : Controller
    {

        private readonly ApplicationDbContext _context;

        public ToDoTasksController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: /<controller>/
        public IActionResult Index()
        {
            var todo = _context.todoTask.ToList();

            return View(todo);
        }

        [HttpGet]
        public IActionResult Create()
        {
            //return RedirectToAction("Index");
            return View();

        }

        [HttpPost]
        public IActionResult Create(ToDoTasks todos)
        {
            if (ModelState.IsValid)
            {
                _context.todoTask.Add(todos);
                _context.SaveChanges();
               return RedirectToAction("Index");
            }
            return View(todos);
        }

    }
}

FullToDoWebsite solution/FullToDoWebsite/Views/ToDoTasks/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model ToDoTasks

@{
}

<form class="" asp-action="Create">
    <input asp-for="Task_todo" id="todo-task" placeholder="New Task">
    <input asp-for="Task_DueDate" id="todo-duedate" placeholder="Due Date">
    <input type="submit" value="Add New Task" class="btn btn-primary" />
    @*<button type="submit"> Add </button>*@
</form>

FullToDoWebsite solution/FullToDoWebsite/Views/ToDoTasks/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<ToDoTasks>

@{
}
<div class="Container card text-center .d-flex" style="width: 35rem;">
    <h1 class="card-header">My ToDo Tasks List </h1>
    <div class="sec-1">
        <div class="suday sec-1-pt-1 p-2">
            
           @*<partial name="/ToDoTasks/PartialView/CreatePartialView" />*@
            <a asp-controller="ToDoTasks" asp-action="Create" class="btn btn- m-2"> Add Task </a>

            <hr>

            @if (Model.Count() > 0)
            {
                @foreach (var item in Model)
                {
                    <div draggable="true" class="task border m-2 p-2">
                        <p> @item.Task_id</p>
                        <input type="checkbox" id="CBtask1">
                        <label for="CBtask1">@item.Task_todo</label>
                        <p>@item.Task_DueDate</p>
                        <a asp-controller="ToDoTasks" asp-action="Update" asp-route-id=@item.Task_id class="btn btn-info m-2 "> Update </a>
                        <a asp-controller="ToDoTasks" asp-action="Delete" asp-route-id=@item.Task_id class="btn btn-danger m-2"> Delete </a>
                    </div>
                }
            }
            else
            {
                <div class=" mt-4 bg-light">
                    <h3>There is no Tasks To Do ..</h3>
                </div>
            }

        </div>
    </div>
</div>

FullToDoWebsite solution/FullToDoWebsite/Views/ToDoTasks/PartialView/CreatePartialView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model ToDoTasks

@{
}
<form class="" asp-action="Create">
    <input asp-for="Task_todo" id="todo-task" placeholder="New Task">
    <input asp-for="Task_DueDate" id="todo-duedate" placeholder="Due Date">
    <input type="submit" value="Add New Task" class="btn btn-primary" />
    @*<button type="submit"> Add </button>*@
</form>